package org.mybatis.scala

import org.mybatis.scala.mapping._
import org.mybatis.scala.session.Session

/**
 * This object provides the feature of creating database tables.
 */
object DatabaseSchema {

  /**
   * Prepares tables for testing.
   * @param session the session object to connect to databases.
   */
  def prepare(implicit session: Session): Unit = {
    createUserTable()
  }

  /**
   * Creates a table containing user data.
   */
  val createUserTable = new Perform {
    def xsql =
      <xsql>
        CREATE TABLE IF NOT EXISTS user(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
        name VARCHAR(64) NOT NULL,
        email VARCHAR(256) NOT NULL,
        PRIMARY KEY (id)
        )
      </xsql>
  }

  def bind = Seq(createUserTable)
}
